## 3D Tensor Voting

$$
\mathbf{V}=\text{sign}(\lambda_2)(\left|\lambda_2\right| - \left|\lambda_1\right|) \mathbf{S}(\mathbf{v}, \mathbf{r}, \mathbf{q}, \sigma) + \text{sign}(\lambda_1)(\left|\lambda_1\right| - \left|\lambda_0\right|) \mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) + \lambda_0 \mathbf{B}(\mathbf{v}, \mathbf{r}, \sigma)
$$
Where:
* $\mathbf{V}\in \mathbb{R}^{3\times 3}$ is the tensor result after voting
* $\mathbf{S}\in \mathbb{R}^{3\times 3}$ is the result of stick tensor voting
* $\mathbf{P}\in \mathbb{R}^{3\times 3}$ is the result of plate tensor voting
* $\mathbf{q}\in \mathbb{R}^{3}$ is the unit vector specifying the stick tensor (voter) orientation
* $\mathbf{v}\in \mathbb{R}^{3}$ is the voter position and $\mathbf{r}\in \mathbb{R}^{3}$ is the receiver
* $\sigma$ is the attenuation factor
* $\lambda_0$ is the smallest eigenvalue and $\lambda_2$ is the largest eigenvalue of the voter tensor

## Stick Tensor

$$
\mathbf{S}(\mathbf{v}, \mathbf{r}, \mathbf{q}, \sigma) = \eta(\sigma_1, \sigma_2, p) D(\mathbf{v}, \mathbf{r}, \mathbf{q}, \sigma_1, \sigma_2, p) (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T
$$
where $\mathbf{R}$ is a rotation matrix specifying the orientation of the receiver relative to the voter:
$$
\mathbf{R} = \mathbf{I} - 2\mathbf{d}\mathbf{d}^T
$$
where $\mathbf{d} = \frac{\mathbf{v} - \mathbf{r}}{\ell}$ is the direction from the voter to receiver and $\ell = ||\mathbf{v} - \mathbf{r}||$ is the distance.

### Decay Function
The decay function describes magnitude of the vote at the receiver:
$$
D(\mathbf{v}, \mathbf{r}, \mathbf{q}, \sigma_1, \sigma_2, p)=e^{-\frac{\ell^2}{\sigma_1^2}}\left[ 1 - (\mathbf{q}^T\mathbf{d})^2 \right]^p + e^{-\frac{\ell^2}{\sigma_2^2}}(\mathbf{q}^T\mathbf{d})^{2p}
$$
where
* $\sigma_1$ is the standard deviation of the decay orthogonal to $\mathbf{q}$
* $\sigma_2$ is the standard deviation of the decay in the direction of $\mathbf{q}$
* $p$ is a refinement term that specifies the *spread* of the vote

Alternatively, the decay function may be represented using trigonometric functions:
$$
D(\theta, \ell, \sigma_1, \sigma_2, p)=e^{-\frac{\ell^2}{\sigma_1^2}} \sin^{2p} \theta + e^{-\frac{\ell^2}{\sigma_2^{2}}}\cos^{2p}\theta
$$
where $\theta=\cos^{-1}\left(\mathbf{q}^T\mathbf{d}\right)$.

### Normalization Term
The normalization term ensures that the integral of the plate tensor voting field is 1, and therefore no additional energy is added or taken away from the image:
$$
\eta(\sigma_1, \sigma_2, p) = \left[ \frac{\pi(2p)!}{2^{2p}(p!)^2}\left(\sigma_1^2 + \sigma_2^2\right) \right]^{-1}
$$

## Plate Tensor
The integral for a plate tensor is given by:
$$
\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \frac{\ell}{\sigma_1^2 + \sigma_2^2}   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\mathbf{I} - \frac{1}{4}
\mathbf{M}
\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right)
$$
where $\alpha = \tan^{-1}\frac{d_y}{d_x}$ and
$$
\mathbf{M} = 
\begin{bmatrix}
\cos(2\alpha)+2 & \sin(2\alpha)\\
\sin(2\alpha) & 2 - \cos(2\alpha)
\end{bmatrix}
$$

---

## Stick Normalization Derivation
The normalization factor $\eta$ scales the decay function by the inverse of its integral:
$$
\eta(\sigma_1, \sigma_2, p) = \int_0^\infty \int_0^{2\pi} D(\mathbf{v}, \mathbf{r}, \mathbf{q}, \sigma_1, \sigma_2, p)\ell \, d\theta \, d\ell
$$
This term can be readily calculated using the trigonometric representation of $D$ and evaluating the double integral in polar coordinates:
$$
\int_0^\infty \int_0^{2\pi} D(\theta, \ell, \sigma_1, \sigma_2)\ell \, d\theta \, d\ell = \int_0^\infty\int_0^{2\pi} \left[e^{-\frac{\ell^2}{\sigma_1^2}} \sin^{2p} \theta + e^{-\frac{\ell^2}{\sigma_2^{2}}}\cos^{2p}\theta\right]\ell \, d\theta \, d\ell
$$
Separating the variables, we get the following definite integrals:
$$
= \int_0^\infty  e^{-\frac{\ell^2}{\sigma_1^2}}\ell \, d\ell \int_0^{2\pi}\sin^{2p} \theta \, d\theta + \int_0^\infty e^{-\frac{\ell^2}{\sigma_2^2}}\ell \, d\ell \int_0^{2\pi}\cos^{2p}\theta \, d\theta
$$
where the first integral across $\ell$ can be solved as the integral of a Gaussian:
$$
 \int_0^\infty  e^{-\frac{\ell^2}{\sigma^2}}\ell \, d\ell =  \frac{\sigma^2}{2}
$$
and both trigonometric integrals are equal since they integrate across the entire circle:
$$
\int_0^{2\pi} \left(\sin^{2}\theta\right)^p \, d\theta = \int_0^{2\pi} \left(\cos^{2}\theta\right)^p \, d\theta = \frac{2\pi(2p)!}{2^{2p}(p!)^2}
$$
The final normalization factor is given by:
$$
\eta(\sigma_1, \sigma_2, p) = \left[ \frac{\pi(2p)!}{2^{2p}(p!)^2}\left(\sigma_1^2 + \sigma_2^2\right) \right]^{-1}
$$

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym

theta = sym.symbols("theta")
phi = sym.symbols("phi")

alpha = sym.symbols("alpha")
beta = sym.symbols("beta")

sin_theta = sym.sin(theta) #sympify("(exp(I*theta)-exp(-I*theta))/(2*I)")
cos_theta = sym.cos(theta) #sympify("(exp(I*theta)+exp(-I*theta))/(2)")

sin_phi = sym.sin(phi) #sympify("(exp(I*phi)-exp(-I*phi))/(2*I)")
cos_phi = sym.cos(phi) #sympify("(exp(I*phi)+exp(-I*phi))/(2)")

sin_alpha = sym.sin(alpha) #sympify("(exp(I*alpha)-exp(-I*alpha))/(2*I)")
cos_alpha = sym.cos(alpha) #sympify("(exp(I*alpha)+exp(-I*alpha))/(2)")

sin_beta = sym.sin(beta) #sympify("(exp(I*beta)-exp(-I*beta))/(2*I)")
cos_beta = sym.cos(beta) #sympify("(exp(I*beta)+exp(-I*beta))/(2)")

sigma1, sigma2, l = sym.symbols("sigma_1, sigma_2, l")
n = sym.symbols("n")

## Plate Tensor Derivation

The integral for a plate tensor is given by:
$$
\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \int_{0}^\pi \eta(\sigma_1, \sigma_2, p) D(\theta, \ell, \sigma_1, \sigma_2, p) (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \ell \, d\beta
$$
where
$$
\mathbf{d}=
\begin{bmatrix}
\cos\alpha \\
\sin\alpha
\end{bmatrix}
\quad
\quad
\mathbf{q}=
\begin{bmatrix}
\cos\beta \\
\sin\beta
\end{bmatrix}
$$
We will assume that $p=1$, since the refinement term doesn't really make sense for a plate tensor in 2D:
$$
= \eta(\sigma_1, \sigma_2, 1) \ell   \int_0^\pi \left[\left(e^{-\frac{\ell^2}{\sigma_1^2}} \sin^{2} \theta + e^{-\frac{\ell^2}{\sigma_2^{2}}}\cos^{2}\theta \right) (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \right]\, d\beta
$$
$$
= \eta(\sigma_1, \sigma_2, 1) \ell   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\int_0^\pi  \left(1 - \left(\mathbf{q}^T\mathbf{d}\right)^2\right) (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta + e^{-\frac{\ell^2}{\sigma_2^2}}\int_0^\pi \left(\mathbf{q}^T\mathbf{d}\right)^2(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta\right)
$$
$$
= \eta(\sigma_1, \sigma_2, 1) \ell   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\int_0^\pi   (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta - \int_0^\pi \left(\mathbf{q}^T\mathbf{d}\right)^2 (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\int_0^\pi \left(\mathbf{q}^T\mathbf{d}\right)^2(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta\right)
$$


where $\mathbf{R}=\mathbf{I}-2\mathbf{d}\mathbf{d}^T$. Combining the outer products into symmetric matrices: $\mathbf{Q}=\mathbf{q}\mathbf{q}^T$ and $\mathbf{D}=\mathbf{d}\mathbf{d}^T$, we can expand the term:
$$
(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T = (\mathbf{I}-2\mathbf{D})\mathbf{Q}(\mathbf{I}-2\mathbf{D})
$$
$$
=(\mathbf{I}\mathbf{Q}-2\mathbf{D}\mathbf{Q})(\mathbf{I}-2\mathbf{D})
$$
$$
=\mathbf{I}\mathbf{Q}\mathbf{I}-2\mathbf{I}\mathbf{Q}\mathbf{D}^T-2\mathbf{D}\mathbf{Q}\mathbf{I}+4\mathbf{D}\mathbf{Q}\mathbf{D}^T
$$
$$
=\mathbf{Q}-2\mathbf{Q}\mathbf{D}^T-2\mathbf{D}\mathbf{Q}+4\mathbf{D}\mathbf{Q}\mathbf{D}^T
$$
where
$$
\mathbf{D}=
\begin{bmatrix}
\cos^2\alpha & \sin\alpha \cos\alpha\\
\sin\alpha \cos\alpha & \sin^2\alpha
\end{bmatrix}
\quad
\quad
\mathbf{Q}=
\begin{bmatrix}
\cos^2\beta & \sin\beta \cos\beta\\
\sin\beta \cos\beta & \sin^2\beta
\end{bmatrix}
$$

The two critical terms to be integrated are:
$$
(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T=\mathbf{Q}-2\mathbf{Q}\mathbf{D}^T-2\mathbf{D}\mathbf{Q}+4\mathbf{D}\mathbf{Q}\mathbf{D}^T
$$
and
$$
(\mathbf{q}^T \mathbf{d})^2(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T = (\mathbf{q}^T \mathbf{d})^2\mathbf{Q} - 2(\mathbf{q}^T \mathbf{d})^2\mathbf{Q}\mathbf{D} - 2(\mathbf{q}^T \mathbf{d})^2\mathbf{D}\mathbf{Q} + 4(\mathbf{q}^T \mathbf{d})^2\mathbf{D}\mathbf{Q}\mathbf{D}^T
$$

Integrating each of these sub-terms across $\beta$ yields:
$$
\int_0^\pi\mathbf{Q}d\theta = \left[\begin{matrix}\frac{\pi}{2} & 0\\0 & \frac{\pi}{2}\end{matrix}\right]
$$

$$
\int_0^\pi\mathbf{Q}\mathbf{D}d\theta = \left[\begin{matrix}\frac{\pi \cos^{2}{\left(\alpha \right)}}{2} & \frac{\pi \sin{\left(2 \alpha \right)}}{4}\\\frac{\pi \sin{\left(2 \alpha \right)}}{4} & \frac{\pi \sin^{2}{\left(\alpha \right)}}{2}\end{matrix}\right]
$$

$$
\int_0^\pi\mathbf{D}\mathbf{Q}d\theta = \left[\begin{matrix}\frac{\pi \cos^{2}{\left(\alpha \right)}}{2} & \frac{\pi \sin{\left(2 \alpha \right)}}{4}\\\frac{\pi \sin{\left(2 \alpha \right)}}{4} & \frac{\pi \sin^{2}{\left(\alpha \right)}}{2}\end{matrix}\right]
$$

$$
\int_0^\pi \mathbf{D}\mathbf{Q}\mathbf{D}d\theta = \left[\begin{matrix}\frac{\pi \cos^{2}{\left(\alpha \right)}}{2} & \frac{\pi \sin{\left(2 \alpha \right)}}{4}\\\frac{\pi \sin{\left(2 \alpha \right)}}{4} & \frac{\pi \sin^{2}{\left(\alpha \right)}}{2}\end{matrix}\right]
$$

$$
\int_0^\pi(\mathbf{q}^T \mathbf{d})^2\mathbf{Q}\, d\theta = \left[\begin{matrix}\frac{\pi \left(\cos{\left(2 \alpha \right)} + 2\right)}{8} & \frac{\pi \sin{\left(2 \alpha \right)}}{8}\\\frac{\pi \sin{\left(2 \alpha \right)}}{8} & \frac{\pi \left(2 - \cos{\left(2 \alpha \right)}\right)}{8}\end{matrix}\right]
$$

$$
\int_0^\pi(\mathbf{q}^T \mathbf{d})^2\mathbf{Q}\mathbf{D}\, d\theta = \left[\begin{matrix}\frac{3 \pi \cos^{2}{\left(\alpha \right)}}{8} & \frac{3 \pi \sin{\left(2 \alpha \right)}}{16}\\\frac{3 \pi \sin{\left(2 \alpha \right)}}{16} & \frac{3 \pi \sin^{2}{\left(\alpha \right)}}{8}\end{matrix}\right]
$$

$$
\int_0^\pi(\mathbf{q}^T \mathbf{d})^2\mathbf{D}\mathbf{Q}\, d\theta = \left[\begin{matrix}\frac{3 \pi \cos^{2}{\left(\alpha \right)}}{8} & \frac{3 \pi \sin{\left(2 \alpha \right)}}{16}\\\frac{3 \pi \sin{\left(2 \alpha \right)}}{16} & \frac{3 \pi \sin^{2}{\left(\alpha \right)}}{8}\end{matrix}\right]
$$

$$
\int_0^\pi(\mathbf{q}^T \mathbf{d})^2\mathbf{D}\mathbf{Q}\mathbf{D}\, d\theta = \left[\begin{matrix}\frac{3 \pi \cos^{2}{\left(\alpha \right)}}{8} & \frac{3 \pi \sin{\left(2 \alpha \right)}}{16}\\\frac{3 \pi \sin{\left(2 \alpha \right)}}{16} & \frac{3 \pi \sin^{2}{\left(\alpha \right)}}{8}\end{matrix}\right]
$$

Collecting these terms and simplifying we get:
$$
\int_0^\pi(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T\, d\theta = \left[\begin{matrix}\frac{\pi}{2} & 0\\0 & \frac{\pi}{2}\end{matrix}\right]
$$

$$
\int_0^\pi (\mathbf{q}^T \mathbf{d})^2(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\theta = \left[\begin{matrix}\frac{\pi \left(\cos{\left(2 \alpha \right)} + 2\right)}{8} & \frac{\pi \sin{\left(2 \alpha \right)}}{8}\\\frac{\pi \sin{\left(2 \alpha \right)}}{8} & \frac{\pi \left(2 - \cos{\left(2 \alpha \right)}\right)}{8}\end{matrix}\right]
$$

Substituting both of these matrices into the full plate tensor equation yields:
$$
\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \eta(\sigma_1, \sigma_2, 1) \ell   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\int_0^\pi   (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta - \int_0^\pi \left(\mathbf{q}^T\mathbf{d}\right)^2 (\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\int_0^\pi \left(\mathbf{q}^T\mathbf{d}\right)^2(\mathbf{R}\mathbf{q})(\mathbf{R}\mathbf{q})^T \, d\beta\right)
$$

$$
= \eta(\sigma_1, \sigma_2, 1) \ell   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\left[\begin{matrix}\frac{\pi}{2} & 0\\0 & \frac{\pi}{2}\end{matrix}\right] - \left[\begin{matrix}\frac{\pi \left(\cos{\left(2 \alpha \right)} + 2\right)}{8} & \frac{\pi \sin{\left(2 \alpha \right)}}{8}\\\frac{\pi \sin{\left(2 \alpha \right)}}{8} & \frac{\pi \left(2 - \cos{\left(2 \alpha \right)}\right)}{8}\end{matrix}\right]\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\left[\begin{matrix}\frac{\pi \left(\cos{\left(2 \alpha \right)} + 2\right)}{8} & \frac{\pi \sin{\left(2 \alpha \right)}}{8}\\\frac{\pi \sin{\left(2 \alpha \right)}}{8} & \frac{\pi \left(2 - \cos{\left(2 \alpha \right)}\right)}{8}\end{matrix}\right]\right)
$$

$$
= \eta(\sigma_1, \sigma_2, 1) \ell \frac{\pi}{2}   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\mathbf{I} - \frac{1}{4}
\begin{bmatrix}
\cos(2\alpha)+2 & \sin(2\alpha)\\
\sin(2\alpha) & 2 - \cos(2\alpha)
\end{bmatrix}\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\begin{bmatrix}
\cos(2\alpha)+2 & \sin(2\alpha)\\
\sin(2\alpha) & 2 - \cos(2\alpha)
\end{bmatrix}\right)
$$

$$
\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \left[ \frac{2\pi}{4}\left(\sigma_1^2 + \sigma_2^2\right) \right]^{-1} \ell \frac{\pi}{2}   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\mathbf{I} - \frac{1}{4}
\mathbf{M}
\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right)
$$

$$
\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \frac{\ell}{\sigma_1^2 + \sigma_2^2}   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\mathbf{I} - \frac{1}{4}
\mathbf{M}
\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right)
$$
where
$$
\mathbf{M} = 
\begin{bmatrix}
\cos(2\alpha)+2 & \sin(2\alpha)\\
\sin(2\alpha) & 2 - \cos(2\alpha)
\end{bmatrix}
$$

### Plate Normalization Derivation
The integral of the 3D plate tensor decay is given by:
$$
\int_0^\infty \int_{-\pi}^\pi\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \int_0^\infty \int_{-\pi}^\pi\frac{\ell}{\sigma_1^2 + \sigma_2^2}   \left(e^{-\frac{\ell^2}{\sigma_1^2}}\left(\mathbf{I} - \frac{1}{4}
\mathbf{M}
\right) + e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right)\ell \, d\theta \, d\ell
$$

$$
\int_0^\infty \int_{-\pi}^\pi\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \int_0^\infty \frac{1}{\sigma_1^2 + \sigma_2^2}\int_{-\pi}^\pi\left(\ell^2e^{-\frac{\ell^2}{\sigma_1^2}}\mathbf{I} - \ell^2e^{-\frac{\ell^2}{\sigma_1^2}}\frac{1}{4}
\mathbf{M} + \ell^2e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right) \, d\theta \, d\ell
$$

$$
\int_0^\infty \int_{-\pi}^\pi\mathbf{P}(\mathbf{v}, \mathbf{r}, \sigma) = \frac{2\pi}{\sigma_1^2 + \sigma_2^2}\int_0^\infty \left(\ell^2e^{-\frac{\ell^2}{\sigma_1^2}}\mathbf{I} - \ell^2e^{-\frac{\ell^2}{\sigma_1^2}}\frac{1}{4}
\mathbf{M} + \ell^2e^{-\frac{\ell^2}{\sigma_2^2}}\frac{1}{4}
\mathbf{M}
\right) \, d\ell
$$

## 3D Implementation

Where
$$
\mathbf{d} =
\begin{bmatrix}
\cos\alpha \sin\beta\\
\sin\alpha\sin\beta\\
\cos\beta
\end{bmatrix}
=
\begin{bmatrix}
d_x\\
d_y\\
d_z
\end{bmatrix}
$$
and
$$
\mathbf{q} =
\begin{bmatrix}
\cos\theta \sin\phi\\
\sin\theta\sin\phi\\
\cos\phi
\end{bmatrix}
=
\begin{bmatrix}
q_x\\
q_y\\
q_z
\end{bmatrix}
$$

The most simplified version of each integral term is given here (they can likely be simplified further):
$$
\int_0^\pi\mathbf{Q}d\theta=2\pi \mathbf{I} \circ
\begin{bmatrix}
1 - q_z^2 & 0 & 0\\
0 & 1 - q_z^2 & 2\sin\phi q_z\\
0 & 2\sin\phi q_z & 2q_z^2
\end{bmatrix}
$$

$$
\int_0^\pi \mathbf{D}\mathbf{Q}\mathbf{D}d\theta =
\left[8 d_y d_z q_z \sin(\phi)+\pi \left(3 d_z^2 q_z^2 - d_z^2 - q_z^2 +1\right)\right]\mathbf{d}\mathbf{d}^T
$$

$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi d_y d_z q_z \left( \left( q_z^2 - 1 \right) \left( d_y^2-3 \right)+3 \left(2 q_z^2 - 1 \right) d_z^2 \right) + 3\pi\left(q_z^4 \left(35d_z^4 - 30d_z^2+3\right) - 6 q_z^2\left(5 d_z^4 - 6d_z^2 + 1\right) + 3\left(z^2-1\right)^2 \right) \right] \mathbf{d}\mathbf{d}^T
$$

## 2D Derivation

In [2]:
# 2D implementation
q = sym.Matrix([[cos_beta], [sin_beta]])
d = sym.Matrix([[cos_alpha], [sin_alpha]])

# define the D and Q matrices
D = d * d.transpose()
Q = q * q.transpose()

In [4]:
Q

Matrix([
[       cos(beta)**2, sin(beta)*cos(beta)],
[sin(beta)*cos(beta),        sin(beta)**2]])

In [5]:
D

Matrix([
[        cos(alpha)**2, sin(alpha)*cos(alpha)],
[sin(alpha)*cos(alpha),         sin(alpha)**2]])

In [7]:
# integrate each term
iQ = sym.integrate(Q, (beta, 0, sym.pi))
iQ = sym.simplify(iQ)
iQ

Matrix([
[pi/2,    0],
[   0, pi/2]])

In [8]:
iDQ = sym.integrate(D*Q, (beta, 0, sym.pi))
iDQ = sym.simplify(iDQ)
iDQ

Matrix([
[pi*cos(alpha)**2/2,  pi*sin(2*alpha)/4],
[ pi*sin(2*alpha)/4, pi*sin(alpha)**2/2]])

In [9]:
iQD = sym.integrate(Q*D, (beta, 0, sym.pi))
iQD = sym.simplify(iQD)
iQD

Matrix([
[pi*cos(alpha)**2/2,  pi*sin(2*alpha)/4],
[ pi*sin(2*alpha)/4, pi*sin(alpha)**2/2]])

In [10]:
iDQD = sym.integrate(D*Q*D, (beta, 0, sym.pi))
iDQD = sym.simplify(iDQD)
iDQD

Matrix([
[pi*cos(alpha)**2/2,  pi*sin(2*alpha)/4],
[ pi*sin(2*alpha)/4, pi*sin(alpha)**2/2]])

In [11]:
qDq = (q.transpose() * D * q)[0]

iqDqQ = sym.integrate(qDq * Q, (beta, 0, sym.pi))
iqDqQ = sym.simplify(iqDqQ)
iqDqQ

Matrix([
[pi*(cos(2*alpha) + 2)/8,       pi*sin(2*alpha)/8],
[      pi*sin(2*alpha)/8, pi*(2 - cos(2*alpha))/8]])

In [12]:
iqDqDQD = sym.integrate(qDq * D * Q * D, (beta, 0, sym.pi))
iqDqDQD = sym.simplify(iqDqDQD)
iqDqDQD

Matrix([
[3*pi*cos(alpha)**2/8, 3*pi*sin(2*alpha)/16],
[3*pi*sin(2*alpha)/16, 3*pi*sin(alpha)**2/8]])

In [14]:
# calculate the final integrals
iRqRq = iQ - 2*iQD - 2*iDQ + 4 * iDQD
iRqRq = sym.simplify(iRqRq)
iRqRq

Matrix([
[pi/2,    0],
[   0, pi/2]])

In [15]:
qd2 = ((q.transpose() * d) **2)[0]

In [16]:
qd2Q = qd2 * Q
iqd2Q = sym.integrate(qd2Q, (beta, 0, sym.pi))
iqd2Q = sym.simplify(iqd2Q)
iqd2Q

Matrix([
[pi*(cos(2*alpha) + 2)/8,       pi*sin(2*alpha)/8],
[      pi*sin(2*alpha)/8, pi*(2 - cos(2*alpha))/8]])

In [17]:
qd2QD = qd2 * Q * D
iqd2QD = sym.integrate(qd2QD, (beta, 0, sym.pi))
iqd2QD = sym.simplify(iqd2QD)
iqd2QD

Matrix([
[3*pi*cos(alpha)**2/8, 3*pi*sin(2*alpha)/16],
[3*pi*sin(2*alpha)/16, 3*pi*sin(alpha)**2/8]])

In [18]:
qd2DQ = qd2 * D * Q
iqd2DQ = sym.integrate(qd2DQ, (beta, 0, sym.pi))
iqd2DQ = sym.simplify(iqd2DQ)
iqd2DQ

Matrix([
[3*pi*cos(alpha)**2/8, 3*pi*sin(2*alpha)/16],
[3*pi*sin(2*alpha)/16, 3*pi*sin(alpha)**2/8]])

In [19]:
qd2DQD = qd2 * D * Q * D
iqd2DQD = sym.integrate(qd2DQD, (beta, 0, sym.pi))
iqd2DQD = sym.simplify(iqd2DQD)
iqd2DQD

Matrix([
[3*pi*cos(alpha)**2/8, 3*pi*sin(2*alpha)/16],
[3*pi*sin(2*alpha)/16, 3*pi*sin(alpha)**2/8]])

In [20]:
iqd2RqRq = iqd2Q - 2 * iqd2QD - 2 * iqd2DQ + 4 * iqd2DQD
iqd2RqRq = sym.simplify(iqd2RqRq)
iqd2RqRq

Matrix([
[pi*(cos(2*alpha) + 2)/8,       pi*sin(2*alpha)/8],
[      pi*sin(2*alpha)/8, pi*(2 - cos(2*alpha))/8]])

## 3D Derivation

In [6]:
alpha = symbols("alpha")
beta = symbols("beta")

q = Matrix([[cos_theta * sin_phi], [sin_theta * sin_phi], [cos_phi]])
d = Matrix([[cos_alpha * sin_beta], [sin_alpha * sin_beta], [cos_beta]])

#q = Matrix([[cos_theta * sin_phi], [sin_theta * sin_phi], [f]])
#d = Matrix([[a], [b], [c]])



# define the D and Q matrices
D = np.matmul(d, d.transpose())
Q = q * q.transpose()
Q

Matrix([
[        sin(phi)**2*cos(theta)**2, sin(phi)**2*sin(theta)*cos(theta), sin(phi)*cos(phi)*cos(theta)],
[sin(phi)**2*sin(theta)*cos(theta),         sin(phi)**2*sin(theta)**2, sin(phi)*sin(theta)*cos(phi)],
[     sin(phi)*cos(phi)*cos(theta),      sin(phi)*sin(theta)*cos(phi),                  cos(phi)**2]])

In [7]:
# integrate each term
iQ = integrate(Q, (theta, 0, pi))
iQ = simplify(iQ)
iQ



Matrix([
[pi*sin(phi)**2/2,                0,              0],
[               0, pi*sin(phi)**2/2,     sin(2*phi)],
[               0,       sin(2*phi), pi*cos(phi)**2]])

In [69]:
iDQD = integrate(D*Q*D, (theta, 0, pi))
iDQD = simplify(iDQD)
iDQD

Matrix([
[        (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(beta)**2*cos(alpha)**2/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)**2*cos(alpha)/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(beta)*cos(alpha)*cos(beta)/2],
[(8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)**2*cos(alpha)/2,         (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)**2*sin(beta)**2/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)*cos(beta)/2],
[    (8*sin(alpha

In [ ]:
qDq = (q.transpose() * D * q)[0]

iqDqQ = integrate(qDq * Q, (theta, 0, pi))
iqDqQ = simplify(iqDqQ)

In [ ]:
iqDqDQD = integrate(qDq * D * Q * D, (theta, 0, pi))
iqDqDQD = simplify(iqDqDQD)

In [ ]:
# calculate the final integral and display
P = iQ + 4 * iDQD - iqDqQ - 4 * iqDqDQD
P = simplify(P)

### Simplify the first term

In [39]:
simplify(iQ)

Matrix([
[pi*sin(phi)**2/2,                0,              0],
[               0, pi*sin(phi)**2/2,     sin(2*phi)],
[               0,       sin(2*phi), pi*cos(phi)**2]])

In [40]:
dx = symbols("d_x")
dy = symbols("d_y")
dz = symbols("d_z")
qz = symbols("q_z")

sub_iQ = iQ.subs(cos_alpha * sin_beta, dx)
sub_iQ = sub_iQ.subs(sin_alpha * sin_beta, dy)
sub_iQ = sub_iQ.subs(cos_beta, dz)
sub_iQ = sub_iQ.subs(cos_phi, qz)
simplify(sub_iQ)

Matrix([
[pi*sin(phi)**2/2,                0,          0],
[               0, pi*sin(phi)**2/2, sin(2*phi)],
[               0,       sin(2*phi),  pi*q_z**2]])

$$
\int_0^\pi\mathbf{Q}d\theta=
\begin{bmatrix}
\frac{\pi \sin^2(\phi)}{2} & 0 & 0\\
0 & \frac{\pi \sin^2(\phi)}{2} & \sin(2\phi)\\
0 & \sin(2\phi) & \pi \cos^2(\phi)
\end{bmatrix}\\
\int_0^\pi\mathbf{Q}d\theta=\pi \mathbf{I} \circ
\begin{bmatrix}
\frac{1 - \cos^2\phi}{2} & 0 & 0\\
0 & \frac{1-cos^2\phi}{2} & 2\sin\phi\cos\phi\\
0 & 2\sin\phi\cos\phi & \cos^2\phi
\end{bmatrix}\\
\int_0^\pi\mathbf{Q}d\theta=2\pi \mathbf{I} \circ
\begin{bmatrix}
1 - q_z^2 & 0 & 0\\
0 & 1 - q_z^2 & 2\sin\phi q_z\\
0 & 2\sin\phi q_z & 2q_z^2
\end{bmatrix}
$$

### Simplify the second term

In [31]:
iDQD

Matrix([
[        (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(beta)**2*cos(alpha)**2/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)**2*cos(alpha)/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(beta)*cos(alpha)*cos(beta)/2],
[(8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)**2*cos(alpha)/2,         (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)**2*sin(beta)**2/2, (8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 3*pi*cos(beta)**2*cos(phi)**2 - pi*cos(beta)**2 - pi*cos(phi)**2 + pi)*sin(alpha)*sin(beta)*cos(beta)/2],
[    (8*sin(alpha

In [35]:
dx = symbols("d_x")
dy = symbols("d_y")
dz = symbols("d_z")
qz = symbols("q_z")

sub_iDQD = iDQD.subs(cos_alpha * sin_beta, dx)
sub_iDQD = sub_iDQD.subs(sin_alpha * sin_beta, dy)
sub_iDQD = sub_iDQD.subs(cos_beta, dz)
sub_iDQD = sub_iDQD.subs(cos_phi, qz)
simplify(sub_iDQD)

Matrix([
[ d_x**2*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2, d_x*d_y*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2, d_x*d_z*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2],
[d_x*d_y*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2,  d_y**2*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2, d_y*d_z*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2],
[d_x*d_z*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2, d_y*d_z*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2,  d_z**2*(8*d_y*d_z*q_z*sin(phi) + 3*pi*d_z**2*q_z**2 - pi*d_z**2 - pi*q_z**2 + pi)/2]])

In [36]:
C1 = (8*dy*dz*qz*sin(phi)+3*pi*dz**2*qz**2-pi*dz**2-pi*qz**2+pi)
2/C1*sub_iDQD

Matrix([
[ d_x**2, d_x*d_y, d_x*d_z],
[d_x*d_y,  d_y**2, d_y*d_z],
[d_x*d_z, d_y*d_z,  d_z**2]])

$$
\int_0^\pi \mathbf{D}\mathbf{Q}\mathbf{D}d\theta =
\left[8 d_y d_z q_z \sin(\phi)+3\pi d_z^2 q_z^2 - \pi d_z^2 - \pi q_z^2 + \pi\right]
\begin{bmatrix}
d_x^2 & d_x d_y & d_x d_z\\
d_x d_y & d_y^2 & d_y d_z\\
d_x d_z & d_y d_z & d_z^2
\end{bmatrix}\\
\int_0^\pi \mathbf{D}\mathbf{Q}\mathbf{D}d\theta =
\left[8 d_y d_z q_z \sin(\phi)+3\pi d_z^2 q_z^2 - \pi d_z^2 - \pi q_z^2 + \pi\right]\mathbf{d}\mathbf{d}^T
$$

### Simplify the third term

In [41]:
iqDqQ

Matrix([
[(-6*pi*sin(alpha)**2*sin(beta)**2*sin(phi)**2 + 32*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 21*pi*sin(beta)**2*sin(phi)**2 - 12*pi*sin(beta)**2 - 12*pi*sin(phi)**2 + 12*pi)*sin(phi)**2/24,                                                                                                     (3*pi*sin(alpha)*sin(beta)*sin(phi) + 16*cos(beta)*cos(phi))*sin(beta)*sin(phi)**3*cos(alpha)/12,                                                                                  (4*sin(alpha)*sin(beta)*sin(phi) + 3*pi*cos(beta)*cos(phi))*sin(beta)*sin(phi)**2*cos(alpha)*cos(phi)/3],
[                                                                                                     (3*pi*sin(alpha)*sin(beta)*sin(phi) + 16*cos(beta)*cos(phi))*sin(beta)*sin(phi)**3*cos(alpha)/12, (6*pi*sin(alpha)**2*sin(beta)**2*sin(phi)**2 + 64*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 15*pi*sin(beta)**2*sin(phi)**2 - 12*pi*sin(beta)**2 - 12*pi*sin(phi)**2 + 12*pi)*sin(phi)**2/24, (2*sin(a

In [42]:
dx = symbols("d_x")
dy = symbols("d_y")
dz = symbols("d_z")
qz = symbols("q_z")

sub_iqDqQ = iqDqQ.subs(cos_alpha * sin_beta, dx)
sub_iqDqQ = sub_iqDqQ.subs(sin_alpha * sin_beta, dy)
sub_iqDqQ = sub_iqDqQ.subs(cos_beta, dz)
sub_iqDqQ = sub_iqDqQ.subs(cos_phi, qz)
simplify(sub_iqDqQ)

Matrix([
[(-6*pi*d_y**2*sin(phi)**2 + 32*d_y*d_z*q_z*sin(phi) + 21*pi*sin(beta)**2*sin(phi)**2 - 12*pi*sin(beta)**2 - 12*pi*sin(phi)**2 + 12*pi)*sin(phi)**2/24,                                                                                                  d_x*(3*pi*d_y*sin(phi) + 16*d_z*q_z)*sin(phi)**3/12,                                                                               d_x*q_z*(4*d_y*sin(phi) + 3*pi*d_z*q_z)*sin(phi)**2/3],
[                                                                                                  d_x*(3*pi*d_y*sin(phi) + 16*d_z*q_z)*sin(phi)**3/12, (6*pi*d_y**2*sin(phi)**2 + 64*d_y*d_z*q_z*sin(phi) + 15*pi*sin(beta)**2*sin(phi)**2 - 12*pi*sin(beta)**2 - 12*pi*sin(phi)**2 + 12*pi)*sin(phi)**2/24, q_z*(2*d_y**2*sin(phi)**2 + 3*pi*d_y*d_z*q_z*sin(phi) + 8*sin(beta)**2*sin(phi)**2 - 6*sin(beta)**2 - 6*sin(phi)**2 + 6)*sin(phi)/3],
[                                                                                                d_x*q_z*(4*d_y*sin(phi

### Simplify the fourth term

In [43]:
iqDqDQD

Matrix([
[                                 (-8*sin(alpha)**3*sin(beta)**3*sin(phi)**3*cos(beta)*cos(phi)/3 + 16*sin(alpha)*sin(beta)**3*sin(phi)**3*cos(beta)*cos(phi) - 8*sin(alpha)*sin(beta)**3*sin(phi)*cos(beta)*cos(phi) - 8*sin(alpha)*sin(beta)*sin(phi)**3*cos(beta)*cos(phi) + 8*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 35*pi*sin(beta)**4*sin(phi)**4/8 - 5*pi*sin(beta)**4*sin(phi)**2 + pi*sin(beta)**4 - 5*pi*sin(beta)**2*sin(phi)**4 + 7*pi*sin(beta)**2*sin(phi)**2 - 2*pi*sin(beta)**2 + pi*sin(phi)**4 - 2*pi*sin(phi)**2 + pi)*sin(beta)**2*cos(alpha)**2, (-64*sin(alpha)**3*sin(beta)**3*sin(phi)**3*cos(beta)*cos(phi) + 384*sin(alpha)*sin(beta)**3*sin(phi)**3*cos(beta)*cos(phi) - 192*sin(alpha)*sin(beta)**3*sin(phi)*cos(beta)*cos(phi) - 192*sin(alpha)*sin(beta)*sin(phi)**3*cos(beta)*cos(phi) + 192*sin(alpha)*sin(beta)*sin(phi)*cos(beta)*cos(phi) + 105*pi*sin(beta)**4*sin(phi)**4 - 120*pi*sin(beta)**4*sin(phi)**2 + 24*pi*sin(beta)**4 - 120*pi*sin(beta)**2*sin(phi)**4 + 168*pi*si

In [48]:
dx = symbols("d_x")
dy = symbols("d_y")
dz = symbols("d_z")
qz = symbols("q_z")

sub_iqDqDQD = iqDqDQD.subs(cos_alpha * sin_beta, dx)
sub_iqDqDQD = sub_iqDqDQD.subs(sin_alpha * sin_beta, dy)
sub_iqDqDQD = sub_iqDqDQD.subs(cos_beta, dz)
sub_iqDqDQD = sub_iqDqDQD.subs(cos_phi, qz)
C1 = -64*dy**3*dz*qz*sin(phi)**3 + 384*dy*dz*qz*sin(beta)**2*sin(phi)**3 - 192*dy*dz*qz*sin(beta)**2*sin(phi) - 192*dy*dz*qz*sin(phi)**3 + 192*dy*dz*qz*sin(phi) + 105*pi*sin(beta)**4*sin(phi)**4 - 120*pi*sin(beta)**4*sin(phi)**2 + 24*pi*sin(beta)**4 - 120*pi*sin(beta)**2*sin(phi)**4 + 168*pi*sin(beta)**2*sin(phi)**2 - 48*pi*sin(beta)**2 + 24*pi*sin(phi)**4 - 48*pi*sin(phi)**2 + 24*pi
simplify(24 /C1 *sub_iqDqDQD)

Matrix([
[ d_x**2, d_x*d_y, d_x*d_z],
[d_x*d_y,  d_y**2, d_y*d_z],
[d_x*d_z, d_y*d_z,  d_z**2]])

$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z \sin^3\phi + 384 d_y d_z q_z \sin^2\beta \sin^3\phi - 192 d_y d_z q_z \sin^2\beta \sin(\phi) - 192 d_y d_z q_z \sin^3\phi + 192 d_y d_z q_z \sin\phi + 105 \pi \sin^4\beta \sin^4\phi - 120 \pi \sin^4\beta \sin^2\phi + 24 \pi \sin^4\beta - 120 \pi \sin^2\beta \sin^4\phi + 168 \pi \sin^2\beta \sin^2\phi - 48 \pi \sin^2\beta + 24 \pi \sin^4\phi - 48 \pi \sin^2\phi + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Substitute $\sin^2\beta = 1-d_z^2$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z \sin^3\phi + 384 d_y d_z q_z (1 - d_z^2) \sin^3\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z \sin^3\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1 - d_z^2)(1 - d_z^2) \sin^4\phi - 120 \pi (1 - d_z^2)(1 - d_z^2) \sin^2\phi + 24 \pi (1 - d_z^2)(1 - d_z^2) - 120 \pi (1 - d_z^2) \sin^4\phi + 168 \pi (1 - d_z^2) \sin^2\phi - 48 \pi (1 - d_z^2) + 24 \pi \sin^4\phi - 48 \pi \sin^2\phi + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Substitute $\sin^2\phi = 1-q_z^2$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z (1 - q_z^2) \sin\phi + 384 d_y d_z q_z (1 - d_z^2) (1 - q_z^2) \sin\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1 - d_z^2)(1 - d_z^2) (1 - q_z^2)(1 - q_z^2) - 120 \pi (1 - d_z^2)(1 - d_z^2) \sin^2\phi + 24 \pi (1 - d_z^2)(1 - d_z^2) - 120 \pi (1 - d_z^2) (1 - q_z^2)(1 - q_z^2) + 168 \pi (1 - d_z^2) (1 - q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1 - q_z^2)(1 - q_z^2) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand $(1-q_z^2)(1-q_z^2)=(1-2q_z^2 + q_z^4)$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z (1 - q_z^2) \sin\phi + 384 d_y d_z q_z (1 - d_z^2) (1 - q_z^2) \sin\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1 - d_z^2)(1 - d_z^2) (1-2q_z^2 + q_z^4) - 120 \pi (1 - d_z^2)(1 - d_z^2) \sin^2\phi + 24 \pi (1 - d_z^2)(1 - d_z^2) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1 - d_z^2) (1 - q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand $(1-d_z^2)(1-d_z^2)=(1-2d_z^2 + d_z^4)$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z (1 - q_z^2) \sin\phi + 384 d_y d_z q_z (1 - d_z^2) (1 - q_z^2) \sin\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1 - d_z^2) (1 - q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand $(1-d_z^2)(1-q_z^2)=(1-d_z^2 - q_z^2 + d_z^2 q_z^2)$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ -64 d_y^3 d_z q_z (1 - q_z^2) \sin\phi + 384 d_y d_z q_z (1-d_z^2 - q_z^2 + d_z^2 q_z^2) \sin\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  + 384 d_y d_z q_z (1-d_z^2 - q_z^2 + d_z^2 q_z^2) \sin\phi - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  - 192 d_y d_z q_z (1 - d_z^2) \sin(\phi) - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  - 192 d_y d_z q_z (1 - q_z^2) \sin\phi + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi + 105 \pi (1-2d_z^2 + d_z^4) (1-2q_z^2 + q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi +  (105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4) - 120 \pi (1-2d_z^2 + d_z^4) \sin^2\phi + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi +  (105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4) -  (120 \pi\sin^2\phi -240 \pi d_z^2\sin^2\phi + 120 \pi d_z^4\sin^2\phi)  + 24 \pi (1-2d_z^2 + d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi +  (105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4) -  (120 \pi\sin^2\phi -240 \pi d_z^2\sin^2\phi + 120 \pi d_z^4\sin^2\phi)  + (24 \pi-48 \pi d_z^2 + 24 \pi d_z^4) - 120 \pi (1 - d_z^2) (1-2q_z^2 + q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi +  (105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4) -  (120 \pi\sin^2\phi -240 \pi d_z^2\sin^2\phi + 120 \pi d_z^4\sin^2\phi)  + (24 \pi-48 \pi d_z^2 + 24 \pi d_z^4) -  (120 \pi - 240\pi q_z^2 + 120 \pi q_z^4 - 120 \pi d_z^2 + 240\pi  d_z^2 q_z^2 - 120 \pi d_z^2 q_z^4) + 168 \pi (1-d_z^2 - q_z^2 + d_z^2 q_z^2) - 48 \pi (1 - d_z^2) + 24 \pi (1-2q_z^2 + q_z^4) - 48 \pi (1 - q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Expand:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  (64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi)  +  (384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z^3 q_z\sin\phi)  -  (192 d_y d_z q_z\sin\phi - 192 d_y d_z q_z^3\sin\phi)  + 192 d_y d_z q_z \sin\phi +  (105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4) -  (120 \pi\sin^2\phi -240 \pi d_z^2\sin^2\phi + 120 \pi d_z^4\sin^2\phi)  + (24 \pi-48 \pi d_z^2 + 24 \pi d_z^4) -  (120 \pi - 240\pi q_z^2 + 120 \pi q_z^4 - 120 \pi d_z^2 + 240\pi  d_z^2 q_z^2 - 120 \pi d_z^2 q_z^4) +  (168 \pi -168 \pi d_z^2 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2) - (48 \pi - 48 \pi d_z^2) +  (24 \pi - 48 \pi q_z^2 + 24 \pi q_z^4) - (48 \pi - 48 \pi q_z^2) + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Distribute signs:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi  +  384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z^3 q_z\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z q_z^3\sin\phi  + 192 d_y d_z q_z \sin\phi + 105 \pi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4 - 120 \pi\sin^2\phi + 240 \pi d_z^2\sin^2\phi - 120 \pi d_z^4\sin^2\phi  + 24 \pi-48 \pi d_z^2 + 24 \pi d_z^4 -  120 \pi + 240\pi q_z^2 - 120 \pi q_z^4 + 120 \pi d_z^2 - 240\pi  d_z^2 q_z^2 + 120 \pi d_z^2 q_z^4 +  168 \pi -168 \pi d_z^2 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2 - 48 \pi + 48 \pi d_z^2 +  24 \pi - 48 \pi q_z^2 + 24 \pi q_z^4 - 48 \pi + 48 \pi q_z^2 + 24 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms with $\pi$ only:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi  +  384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z^3 q_z\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z q_z^3\sin\phi  + 192 d_y d_z q_z \sin\phi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4 - 120 \pi\sin^2\phi + 240 \pi d_z^2\sin^2\phi - 120 \pi d_z^4\sin^2\phi  -48 \pi d_z^2 + 24 \pi d_z^4 + 240\pi q_z^2 - 120 \pi q_z^4 + 120 \pi d_z^2 - 240\pi  d_z^2 q_z^2 + 120 \pi d_z^2 q_z^4 -168 \pi d_z^2 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2 + 48 \pi d_z^2  - 48 \pi q_z^2 + 24 \pi q_z^4 + 48 \pi q_z^2 + 129 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Cancel easy terms:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi  +  384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z^3 q_z\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z q_z^3\sin\phi  + 192 d_y d_z q_z \sin\phi - 210\pi q_z^2 + 105 \pi q_z^4 - 210\pi d_z^2 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4 - 120 \pi\sin^2\phi + 240 \pi d_z^2\sin^2\phi - 120 \pi d_z^4\sin^2\phi  -48 \pi d_z^2 + 24 \pi d_z^4 + 240\pi q_z^2 - 120 \pi q_z^4 + 120 \pi d_z^2 - 240\pi  d_z^2 q_z^2 + 120 \pi d_z^2 q_z^4 -168 \pi d_z^2 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2 + 48 \pi d_z^2  + 24 \pi q_z^4 + 129 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms with $\pi d_z^2$ only:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[  64 d_y^3 d_z q_z^3\sin\phi - 64 d_y^3 d_z q_z\sin\phi  +  384 d_y d_z q_z\sin\phi-384 d_y d_z^3 q_z\sin\phi - 384 d_y d_z q_z^3\sin\phi + 384 d_y d_z^3 q_z^3\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z^3 q_z\sin\phi  - 192 d_y d_z q_z\sin\phi + 192 d_y d_z q_z^3\sin\phi  + 192 d_y d_z q_z \sin\phi - 210\pi q_z^2 + 105 \pi q_z^4 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4 - 120 \pi\sin^2\phi + 240 \pi d_z^2\sin^2\phi - 120 \pi d_z^4\sin^2\phi  + 24 \pi d_z^4 + 240\pi q_z^2 - 120 \pi q_z^4 - 240\pi  d_z^2 q_z^2 + 120 \pi d_z^2 q_z^4 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2 -258 \pi d_z^2  + 24 \pi q_z^4 + 129 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Factor out $\sin\phi$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ \sin\phi\left( 64 d_y^3 d_z q_z^3 - 64 d_y^3 d_z q_z  +  384 d_y d_z q_z-384 d_y d_z^3 q_z - 384 d_y d_z q_z^3 + 384 d_y d_z^3 q_z^3  - 192 d_y d_z q_z + 192 d_y d_z^3 q_z  - 192 d_y d_z q_z + 192 d_y d_z q_z^3  + 192 d_y d_z q_z \right) - 210\pi q_z^2 + 105 \pi q_z^4 + 420\pi d_z^2 q_z^2 - 210\pi d_z^2 q_z^4 + 105 \pi d_z^4 - 210\pi d_z^4 q_z^2 + 105 \pi d_z^4 q_z^4 - 120 \pi\sin^2\phi + 240 \pi d_z^2\sin^2\phi - 120 \pi d_z^4\sin^2\phi  + 24 \pi d_z^4 + 240\pi q_z^2 - 120 \pi q_z^4 - 240\pi  d_z^2 q_z^2 + 120 \pi d_z^2 q_z^4 - 168 \pi q_z^2 + 168 \pi d_z^2 q_z^2 -258 \pi d_z^2  + 24 \pi q_z^4 + 129 \pi \right] \mathbf{d}\mathbf{d}^T
$$
Factor out $\pi$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ \sin\phi\left( 64 d_y^3 d_z q_z^3 - 64 d_y^3 d_z q_z  +  384 d_y d_z q_z-384 d_y d_z^3 q_z - 384 d_y d_z q_z^3 + 384 d_y d_z^3 q_z^3  - 192 d_y d_z q_z + 192 d_y d_z^3 q_z  - 192 d_y d_z q_z + 192 d_y d_z q_z^3  + 192 d_y d_z q_z \right) + \pi\left(- 210 q_z^2 + 105 q_z^4 + 420 d_z^2 q_z^2 - 210 d_z^2 q_z^4 + 105 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 24 d_z^4 + 240 q_z^2 - 120 q_z^4 - 240 d_z^2 q_z^2 + 120 d_z^2 q_z^4 - 168 q_z^2 + 168 d_z^2 q_z^2 -258 d_z^2 + 24 q_z^4 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Simplify terms with $d_y d_z q_z$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ \sin\phi\left( 64 d_y^3 d_z q_z^3 - 64 d_y^3 d_z q_z  +  192 d_y d_z q_z-384 d_y d_z^3 q_z - 384 d_y d_z q_z^3 + 384 d_y d_z^3 q_z^3  + 192 d_y d_z^3 q_z  + 192 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 105 q_z^4 + 420 d_z^2 q_z^2 - 210 d_z^2 q_z^4 + 105 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 24 d_z^4 + 240 q_z^2 - 120 q_z^4 - 240 d_z^2 q_z^2 + 120 d_z^2 q_z^4 - 168 q_z^2 + 168 d_z^2 q_z^2 -258 d_z^2 + 24 q_z^4 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Factor out $64$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 105 q_z^4 + 420 d_z^2 q_z^2 - 210 d_z^2 q_z^4 + 105 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 24 d_z^4 + 240 q_z^2 - 120 q_z^4 - 240 d_z^2 q_z^2 + 120 d_z^2 q_z^4 - 168 q_z^2 + 168 d_z^2 q_z^2 -258 d_z^2 + 24 q_z^4 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms with $d_z^2 q_z^2$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 105 q_z^4 + 348 d_z^2 q_z^2 - 210 d_z^2 q_z^4 + 105 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 24 d_z^4 + 240 q_z^2 - 120 q_z^4 + 120 d_z^2 q_z^4 - 168 q_z^2 -258 d_z^2 + 24 q_z^4 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms with $d_z^2 q_z^4$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 105 q_z^4 + 348 d_z^2 q_z^2 - 90 d_z^2 q_z^4 + 105 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 24 d_z^4 + 240 q_z^2 - 120 q_z^4 - 168 q_z^2 -258 d_z^2 + 24 q_z^4 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms with $d_z^4$ and $q_z^4$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 9 q_z^4 + 348 d_z^2 q_z^2 - 90 d_z^2 q_z^4 + 129 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120\sin^2\phi + 240 d_z^2\sin^2\phi - 120 d_z^4\sin^2\phi  + 240 q_z^2 - 168 q_z^2 -258 d_z^2 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Missed a couple of $\sin^2\phi = (1-q_z^2)$:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 9 q_z^4 + 348 d_z^2 q_z^2 - 90 d_z^2 q_z^4 + 129 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120(1-q_z^2) + 240 d_z^2(1-q_z^2) - 120 d_z^4(1-q_z^2)  + 240 q_z^2 - 168 q_z^2 -258 d_z^2 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Expand those terms:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 9 q_z^4 + 348 d_z^2 q_z^2 - 90 d_z^2 q_z^4 + 129 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - (120-120 q_z^2) + (240 d_z^2 -240 d_z^2 q_z^2) - (120 d_z^4- 120 d_z^4 q_z^2)  + 240 q_z^2 - 168 q_z^2 -258 d_z^2 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Distribute the signs:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(- 210 q_z^2 + 9 q_z^4 + 348 d_z^2 q_z^2 - 90 d_z^2 q_z^4 + 129 d_z^4 - 210 d_z^4 q_z^2 + 105 d_z^4 q_z^4 - 120 + 120 q_z^2 + 240 d_z^2 -240 d_z^2 q_z^2 - 120 d_z^4 + 120 d_z^4 q_z^2  + 240 q_z^2 - 168 q_z^2 -258 d_z^2 + 129\right) \right] \mathbf{d}\mathbf{d}^T
$$
Collect terms:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 6 d_y d_z^3 q_z - 6 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  + 3 d_y d_z^3 q_z  + 3 d_y d_z q_z^3 \right) + \pi\left(105 d_z^4 q_z^4 + 9 d_z^4 + 9 q_z^4 - 90 d_z^4 q_z^2 - 90 d_z^2 q_z^4 + 108 d_z^2 q_z^2 -18 d_z^2 - 18 q_z^2 + 9\right) \right] \mathbf{d}\mathbf{d}^T
$$
Collect more terms at the front:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi\left( d_y^3 d_z q_z^3 - d_y^3 d_z q_z  +  3 d_y d_z q_z- 3 d_y d_z^3 q_z - 3 d_y d_z q_z^3 + 6 d_y d_z^3 q_z^3  \right) + \pi\left(105 d_z^4 q_z^4 + 9 d_z^4 + 9 q_z^4 - 90 d_z^4 q_z^2 - 90 d_z^2 q_z^4 + 108 d_z^2 q_z^2 -18 d_z^2 - 18 q_z^2 + 9\right) \right] \mathbf{d}\mathbf{d}^T
$$
Simplify with Wolfram:
$$
\int_0^\pi \mathbf{q}^T \mathbf{D}\mathbf{q}\mathbf{D}\mathbf{Q}\mathbf{D} d\theta=
\frac{1}{24}\left[ 64\sin\phi d_y d_z q_z \left( \left( q_z^2 - 1 \right) \left( d_y^2-3 \right)+3 \left(2 q_z^2 - 1 \right) d_z^2 \right) + 3\pi\left(q_z^4 \left(35d_z^4 - 30d_z^2+3\right) - 6 q_z^2\left(5 d_z^4 - 6d_z^2 + 1\right) + 3\left(z^2-1\right)^2 \right) \right] \mathbf{d}\mathbf{d}^T
$$